# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
workspace 'Nonton'
 
target 'Nonton' do
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'RealmSwift'
  pod 'SDWebImageSwiftUI'
end

target 'NCore' do
  project '../NCore/NCore'
  pod 'RealmSwift'
end

target 'NFavorite' do
  project '../NFavorite/NFavorite'
  #pod 'NCore', :path => '../NCore/NCore'
  pod 'RealmSwift'
end

target 'NDetail' do
  project '../NDetail/NDetail'
  #pod 'NCore', :path => '../NCore/NCore'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'SDWebImageSwiftUI'
end

target 'NHome' do
  project '../NHome/NHome'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'SDWebImageSwiftUI'
end


